#!/bin/sh
exec 2>&1 # pipe stderr to stdout
echo "STARTED SERVICE: nginx-service"
## Add your service task command below
## Call your service with exec command
exec nginx -c /conf/nginx.conf -g 'daemon off;'
